name: crypto_offline
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  provider: 6.0.2
  flutter_bloc: ^7.0.1
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.6
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  permission_handler: ^8.3.0
  connectivity: ^3.0.6
  google_fonts: 4.0.3

  webview_flutter: ^3.0.0
  url_launcher: ^6.0.18
  local_auth: 2.1.6
  double_back_to_close: 2.0.0
  expandable: 5.0.1

  sqflite_sqlcipher: 2.2.0
  path_provider: ^2.0.20
  fluttertoast: ^8.0.7
  sizer: ^2.0.13
  archive: ^3.1.1
  share: ^2.0.4
  receive_sharing_intent: ^1.4.5
  device_info_plus: 5.0.1

  # cupertino_icons: ^0.1.2
  cupertino_icons: ^1.0.0
  roundcheckbox: ^2.0.3
  cached_network_image: ^3.2.0
  flutter_launcher_icons: ^0.9.2
  get_storage: ^2.0.3

  flutter:
    sdk: flutter

  http: ^0.13.3
  package_info: ^2.0.2
  flutter_svg: ^0.22.0
  flutter_markdown: ^0.6.7

dev_dependencies:
  hive_generator: ^1.1.1
  build_runner: ^2.1.4
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0
  sqflite:
    git:
      url: https://www.github.com/davidmartos96/sqflite_sqlcipher.git
      path: sqflite
      ref: fmdb_override

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/icons/icon.png"


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/background/
    - assets/translations/
    - assets/image/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 400

    - family: MyriadPro
      fonts:
        - asset: fonts/MyriadPro-SemiCn.ttf



